apiVersion: apps/v1
kind: Deployment
metadata:
  name: raj-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: raj-springboot
  template:
    metadata:
      labels:
        app: raj-springboot
    spec:
      containers:
        - name: springboot
          image: coniferrkishor0874/dockerdemo:v1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: raj-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: raj-springboot
